### ISSUE TITLE
As a registered User I want to be able to change my username and password.

### ISSUE THREAD

**Issue by mirovv** [sopra-fs23-group-23/werewolf-server#3]
Task List frontend:
 - [x] sopra-fs23-group-23/werewolf-client#62

Task List backend:
 - [x] #119

Acceptance Criteria:
- In a profile view, the player can change his/her username and set a profile picture.
- By clicking the update button, those changes are saved permanently.

**Comment by ChlineSaurus** [comment]
commit b53534a solves this issue but was mentioned wrong
